version: '3'
services:
  db:
    container_name: mysql-login
    build:
      context: ./db
    image: mysql-login
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  api:
    container_name: login-service
    image: localhost:5000/api-login
    depends_on:
      - db    
  proxy:
    container_name: nginx-proxy
    build:
      context: ./proxy
    image: proxy-login
    ports:
      - "10443:443"
    depends_on:
      - api
