version: '3'
services:
  db:
    container_name: mysql-login
    build:
      context: ./db
    image: mysql-login
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  api:
    container_name: login-service
    build:
      context: ./api
    depends_on:
      - db    
  proxy:
    container_name: nginx-proxy
    build:
      context: ./proxy
    image: proxy-login
    volumes:
      - /etc/ssl/localhost/localhost.crt/localhost.crt:/etc/ssl/certs/localhost.crt
      - /etc/ssl/localhost/localhost.key/localhost.key:/etc/ssl/certs/localhost.key
    ports:
      - "10443:443"
    depends_on:
      - api
